alias ssh-hack="ssh ainsley@188.172.154.182 -p 1022"
alias serve-php="php -S localhost:8000"
alias web="cd ~/desktop/web"
alias reddico='cd ~/desktop/reddico'
alias c='clear'
alias coverage="go test -coverprofile /tmp/c.out && uncover /tmp/c.out"
alias hosts="nano /etc/hosts"
alias efi="~/Documents/Tools/MountEFI/MountEFI.command"
alias propertree="~/Documents/Tools/ProperTree/ProperTree.command"
alias usbmap="~/Documents/Tools/USBMap/USBMap.command"
